// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
// Lógica de KPI por sucursal, oficial, mes, comparación, semáforo, agrupación, heatmap, filtros dinámicos
